version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - database.env

  db_backup:
    image: kulti/tl-db-backup:${IMAGE_TAG}
    env_file:
      - database.env
    environment:
      - POSTGRES_HOST=db

  db_migrations:
    image: kulti/tl-migrate:${IMAGE_TAG}
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      - POSTGRES_DB_HOST=db
    command: version

  tl_server:
    image: kulti/tl-server:${IMAGE_TAG}
    restart: always
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      - POSTGRES_DB_HOST=db
      - PORT=80

  tl_front:
    image: kulti/tl-front:${IMAGE_TAG}
    restart: always

  tl_proxy:
    image: kulti/tl-proxy:${IMAGE_TAG}
    restart: always
    depends_on:
      - tl_front
      - tl_server
