/*
 * Task List
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_cli
// UpdatedPoints struct for UpdatedPoints
type UpdatedPoints struct {
	Burnt int32 `json:"burnt"`
	Points int32 `json:"points"`
}
