/*
 * Task List
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_cli
// Sprint struct for Sprint
type Sprint struct {
	Title string `json:"title"`
}
