run:
  timeout: 1m
  skip-dirs:
    - generated
    - vendor

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    # - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    # - wsl

linters-settings:
  lll:
    line-length: 110
  goimports:
    local-prefixes: github.com/kulti/task-list/server

issues:
  exclude-rules:
    - path: (_test\.go|apitest)
      linters:
        - gosec # security is not make sense in tests
        - noctx # it's ok to do simple http request without context in tests

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
