name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: ./scripts/go_test.sh
        working-directory: server
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          working-directory: server
          path-to-profile: coverage.txt
          ignore: generated,apitest

  integration-tests:
    runs-on: ubuntu-18.04

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make run-tl-integration-tests

  pre-commit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: install dependencies
        run: npm install
        working-directory: front
      - name: generate openapi-cli
        run: make gen-ts
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17
        id: go
      - name: Set up mockgen
        run: GO111MODULE=on go install github.com/golang/mock/mockgen@v1.4.3
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
        env:
          SKIP: unit-tests
