name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Docker login
        uses: azure/container-actions/docker-login@master
        with:
          username: kulti
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish
        run: make push-docker-images
